# Generated by Django 4.2.2 on 2023-09-14 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_usermodel_managers_usermodel_firstname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.ImageField(blank=True, default=None, upload_to='productImages/'),
        ),
    ]
