# Generated by Django 4.2.2 on 2023-09-15 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_product_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='categories',
            new_name='category',
        ),
    ]
