# Generated by Django 4.2.2 on 2023-09-23 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_categories_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='likedByUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='favorite', to='api.usermodel'),
        ),
    ]
