# Generated by Django 4.2.2 on 2023-09-23 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_product_likedbyuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='likedByUser',
        ),
        migrations.AddField(
            model_name='product',
            name='likedByUser',
            field=models.ManyToManyField(to='api.usermodel'),
        ),
    ]
